name: Go Code Base Management
run-name: Run PR management for `${{ github.ref }}`, triggered by @${{ github.actor }}

on:
  pull_request:
    paths:
      - example/**
      - .github/workflows/go-cicd.yaml
  push:
    branches:
      - main
    paths:
      - example/**
      - .github/workflows/go-cicd.yaml

env:
  GO_VERSION: 1.20.5
  GO_WORKING_DIR: ./example/with-test/

jobs:
  build:
    name: Build, Test, Check Test Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "${{ env.GO_VERSION }}"

      - name: Restore cache
        id: go-cache
        uses: actions/cache/restore@v3
        with:
          # Any location that we generate the test coverage report in
          path: |
            ~/.cache/coverage.txt
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-${{ hashFiles('**') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: go build
        run: |
          go build ./...
        working-directory: "${{ env.GO_WORKING_DIR }}"
      - name: go test
        run: |
          go test ./... -coverprofile /tmp/coverage.out -covermode count
        working-directory: "${{ env.GO_WORKING_DIR }}"

      # NOTE: If you want to debug the output interactively, comment this
      #       step in, which would give you an SSH session.
      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@v3

      - name: Check test coverage
        run: |
          ## Step 1. Check previous coverage
          if [[ -f ~/.cache/coverage.txt ]]; then
          prevCoverage=$(cat ~/.cache/coverage.txt)
          echo "Previous test coverage: ${prevCoverage}% (taken from the cache)"
          else
          echo "Previous test coverage: Not found"
          fi

          ## Step 2. Check new coverage
          # Get into directory so that go tool cover can work
          cd "${{ env.GO_WORKING_DIR }}"
          newCoverage=$(go tool cover -func=/tmp/coverage.out | grep total | grep -Eo '[0-9]+\.[0-9]+')
          echo "New test coverage:      ${newCoverage}%"
          echo "${newCoverage}" > /tmp/coverage.txt
          echo

          ## Step 3. Check new coverage >= previous coverage
          isNewWorse=$(bc <<< $prevCoverage > $newCoverage)
          if (( $isNewWorse )); then
          echo "ERROR: The new coverage is worse than the previous coverage, exiting as a failed check"
          exit 1
          else
          echo "The new coverage is greater or equal to the previous coverage."
          fi

      - name: Copy coverage information for cache
        if: always() &&
          github.event_name != 'pull_request'
        run: |
          cp /tmp/coverage.txt ~/.cache/coverage.txt

      - name: Save cache
        if: always() &&
          github.event_name != 'pull_request'
        uses: actions/cache/save@v3
        with:
          key: ${{ steps.go-cache.outputs.cache-primary-key }}
          # Any location that we generate the test coverage report in
          path: |
            ~/.cache/coverage.txt
            ~/.cache/go-build
            ~/go/pkg/mod
